 # Branch whitelist
branches:
  only:
    - master
# Caching of bower_components & node_modules disabled, due to an increase in delayed breakages
cache:
  directories: null
dist: trusty
language: node_js
node_js:
  - '8'
notifications:
  email:
    on_success: never
    on_failure: change
  # slack:
  #   # Custom template used because SUCCESS/FAILURE is all the way at the end by default
  #   template:
  #     - '%{result}: %{repository} <%{build_url}|#%{build_number}>  (<%{compare_url}|%{commit}>)'
  #     - "\tin %{duration} for %{author}'s commit:"
  #     - "\t\"%{commit_subject}\""
  #   rooms:
  #     - '#room-name'
  #   on_pull_requests: false
  #   on_success: always
  #   on_failure: change
  #   on_start: never

before_install:
  # Create .netrc for private repo install
  - 'echo -e "machine github.com\n  login $GITHUB_AUTH_TOKEN" >> ~/.netrc'
install:
  - npm install
before_script:
  - bin/before_script.sh
script:
  - 'npm run standard && npx nyc mocha test/global-config.js test/*-test.js'
after_success:

after_failure:

after_script:
  - bin/after_script.sh
